version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: safetyfire-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "safetyfire"
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci",
        "--default-time-zone=+08:00"
      ]
    volumes:
      - ./.data/mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: safetyfire-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: safetyfire-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./.data/mosquitto:/mosquitto/data
